wsl --install -d Ubuntu
winget install -e SumatraPDF.SumatraPDF
winget install -e AppbyTroye.KoodoReader
winget install -e SublimeHQ.SublimeText.4
winget install -e Python.Python.3.12
winget install -e Ghisler.TotalCommander
winget install -e GoLang.Go
winget install -e Microsoft.PowerShell
winget install -e Google.Chrome
winget install -e Git.Git
winget install -e Gyan.FFmpeg.Essentials
winget install -e KeePassXCTeam.KeePassXC
winget install -e SamHocevar.WinCompose
